config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments, only: :create do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :edit, :create, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 5 }
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{ |post| post.votes_total }.reverse

    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
      format.xml { render xml: @post }
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Your post was created!'
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = 'This post was updated!'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on a post once."
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    access_denied unless logged_in? && (@post.creator == current_user || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="control-group">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |category_box| %>
        <%= category_box.label(class: 'checkbox inline') { category_box.check_box(class: 'checkbox') + category_box.text } %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? "Create a post" : "Update post", class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="well span0 text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: :post, remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br />
    <% end %>
    <span id="post_<%= post.id %>_votes"><%= post.votes_total %></span> votes
    <% if logged_in? %>
      <br />
      <%= link_to vote_post_path(post, vote: false), method: :post, remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quite">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime post.created_at %></small>
    </p>
    <small><span><%= link_to("#{post.comments.size} comments", post_path(post)) %></span></small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? && (@post.creator == current_user || current_user.admin? ) %>
<p class="pull-right">
  [<%= link_to 'edit this post', edit_post_path(@post) %>]
</p>
<% end %>
<p>
  <%= render @post.categories %>
</p>
<%= render 'shared/content_title', title: @post.title %>
<p><%= @post.description %></p>
<hr />
<% if logged_in? %>
<%= form_for [@post, @comment] do |f| %>
  <%= render 'shared/errors', obj: @comment %>
  <div class="control-group">
    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
  </div>
  <%= f.submit "Create commit", class: 'btn btn-primary' %>
<% end %>
<% end %>
<h5>Comments:</h5>
<%= render @post.comments %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
    $("#post_<%= @post.id %>_votes").html('<%= @post.votes_total %>');
<% else %>
    alert('You can only vote on a post once.')
<% end %>